## Automobile Training

In [43]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [44]:
DataSet = pd.read_csv("CarCompanies/FullDataSet.csv")
DataSet.fillna
X = DataSet.iloc[:, 3:].values

In [45]:
Y = DataSet.iloc[:, 2].values
X_opt = X[:,[1,3,5,7,9]]

In [46]:
np.nan_to_num(X_opt)

array([[-1., -1., -1., -1.,  1.],
       [-1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1.,  1.],
       ...,
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_opt, Y, test_size = 0.2, random_state = 0)

In [48]:
np.nan_to_num(X_train)

array([[-1., -1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1., -1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1.],
       [ 1.,  1., -1.,  1.,  1.],
       [-1., -1., -1., -1., -1.],
       [ 1.,  0., -1.,  1.,  1.],
       [ 1.,  1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [-1., -1., -1., -1., -1.],
       [ 1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1., -1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [-1., -1., -1.,  1.,  1.],
       [ 1.,  1., -1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1., -1., -1.],
       [ 1.,  1.,  1.,  1., -1.],
       [-1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [-1.,  

In [49]:
np.nan_to_num(Y_train)

array([-1, -1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,
        1, -1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1,
       -1,  1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  1,
        1,  1, -1,  1, -1,  0,  1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1,  1,
       -1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1, -1,  1,  1,  1,
        1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,
        1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1,
        1,  1, -1, -1,  1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1, -1,
       -1,  1, -1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1,
       -1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1, -1, -1])

In [50]:
np.any(np.isnan(X_train))

False

In [51]:
np.any(np.isnan(Y_train))

False

In [52]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [53]:
y_prediction = regressor.predict(X_test)
output= []
for i in y_prediction:
    output.append(np.sign(i))


### Accuracy

In [57]:
count = 0
for i in range(50):
    if Y_test[i] == output[i]:
        count += 1

In [55]:
percent = (count / 50) * 100

In [56]:
print('%d Percent Accuracy' % percent)

54 Percent Accuracy


In the automobile training, I pulled one year of closing prices (250 days considering weekends and hollidays the market is closed) from 5 prominent automobile companies. These companies were Ford, Fiat Chrystler, General Motors, Honda, and Toyota. I then trained a model which would make a prediction based on the rise or fall of a stock price based on how these companies acted within a day. Once these predictions were made using a logistic regression method, I compared them to the testing section of the Tesla stock and found an accuracy of 54%.

## Tech Training 

In [58]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [59]:
DataSet = pd.read_csv("TechCompanies/FullDataSetTech.csv")
X = DataSet.iloc[:, 3:].values

In [60]:
Y = DataSet.iloc[:, 2].values
X_opt = X[:,[1,3,5,7,9]]

In [65]:
np.nan_to_num(X_opt)

array([[ 1., -1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1.],
       [ 1., -1., -1., -1.,  1.],
       ...,
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_opt, Y, test_size = 0.2, random_state = 0)

In [66]:
np.nan_to_num(X_train)

array([[ 1.,  1., -1.,  1.,  1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       ...,
       [-1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [-1., -1., -1., -1., -1.]])

In [67]:
np.nan_to_num(Y_train)

array([-1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1, -1,
       -1,  1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,  1, -1,
        1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
        1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,
       -1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1,
       -1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1,
       -1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1,
        1,  1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,
        1, -1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
       -1, -1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,
       -1, -1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1, -1, -1])

In [69]:
np.any(np.isnan(X_train))

False

In [70]:
np.any(np.isnan(Y_train))

False

In [71]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [72]:
y_prediction = regressor.predict(X_test)
output= []
for i in y_prediction:
    output.append(np.sign(i))

### Accuracy

In [73]:
count = 0
for i in range(50):
    if Y_test[i] == output[i]:
        count += 1

In [74]:
percent = (count / 50) * 100

In [75]:
print('%d Percent Accuracy' % percent)

70 Percent Accuracy


When training the tech companies model, I again pulled one year of closing price data, this time from 5 prominent tech companies. These companies being Apple, Google, Netflix, Amazon and Facebook. I trained this model in the same fassion using a logistic regression algorithm. When looking at this portfolios relation to Tesla, I found the accuracy to be 70%.